name: maque
url: http://maque.github.io
description: Glimbing a ladder of IT perfection

permalink: /:title/
paginate: 10
highlighter: pygments

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
gems: ['jekyll-paginate','jekyll-tagging']
